// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyB_ClwVlMjVxm7lckpoVLmAnV9O5LCr4XI",
      authDomain: "ehealth-391df.firebaseapp.com",
      projectId: "ehealth-391df",
      storageBucket: "ehealth-391df.firebasestorage.app",
      messagingSenderId: "255898077293",
      appId: "1:255898077293:web:6012cf04d8c6e978559764",
      measurementId: "G-2YLC9D57L9");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv28h-Zp2q-bw1AhiPT0-rtVvM-9LBFQI',
    appId: '1:131647123287:android:d9d8893b246e5f78d89812',
    messagingSenderId: '131647123287',
    projectId: 'health-app-99603',
    databaseURL: 'https://health-app-99603-default-rtdb.firebaseio.com',
    storageBucket: 'health-app-99603.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB45rGly5QSTN-jF4qez-GSyB0U8G6WD8M',
    appId: '1:131647123287:ios:db03c51f647df00dd89812',
    messagingSenderId: '131647123287',
    projectId: 'health-app-99603',
    databaseURL: 'https://health-app-99603-default-rtdb.firebaseio.com',
    storageBucket: 'health-app-99603.appspot.com',
    iosClientId:
        '131647123287-bs4vp3qrgi8cqnt1rg26nhjtfa0d2qj9.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthApp',
  );
}
